2024-11-05 02:57:22,156 -|- WARNING -|- Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Practica\pythonProject1\Bloc12\Lesson_4\tests_12_4.py", line 22, in test_run
    runner_2 = r.Runner(5)
  File "D:\Practica\pythonProject1\Bloc12\Lesson_4\tests_12_1.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-05 02:57:22,157 -|- WARNING -|- Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Practica\pythonProject1\Bloc12\Lesson_4\tests_12_4.py", line 12, in test_walk
    runner_1 = r.Runner('Вася', -5)
  File "D:\Practica\pythonProject1\Bloc12\Lesson_4\tests_12_1.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
